title: "Titolo annuncio"
labels: ["annuncio"]
body:
  - type: input
    id: oggetto
    attributes:
      label: Oggetto
      placeholder: Es. Convocazione Assemblea AIB – marzo 2026
    validations:
      required: true
  - type: textarea
    id: testo
    attributes:
      label: Annuncio
      placeholder: Inserisci il testo completo
    validations:
      required: true
  - type: input
    id: contatti
    attributes:
      label: Contatti
      placeholder: Inserisci mail o numero di telefono
  - type: input
    id: link
    attributes:
      label: Link / allegati
      placeholder: Inserisci link a documenti o pagine
  - type: input
    id: discussione
    attributes:
      label: Link discussione
      placeholder: Inserisci link a discussione
  - type: input
    id: voto
    attributes:
      label: Link votazione
      placeholder: Inserisci link a votazione