title: "Titolo"
labels: ["discussione"]
body:
  - type: input
    id: oggetto
    attributes:
      label: Oggetto
      placeholder: Es. Comunicazione interna, strumenti collaborativi, visione futura
    validations:
      required: true
  - type: textarea
    id: contesto
    attributes:
      label: Contesto
      description: Spiega brevemente perché questo tema è rilevante
      placeholder: Contesto minimo per avviare la discussione
  - type: input
    id: discussione
    attributes:
      label: Discussione
      description: Avvia la discussione. Può essere una riflessione, un’idea, un dubbio aperto.
      placeholder: Scrivi liberamente…
    validations:
      required: true
  - type: input
    id: riferimenti
    attributes:
      label: Link / riferimenti
      placeholder: Documenti, discussioni, risorse esterne
  - type: input
    id: topic
    attributes:
      label: Link discussione
      placeholder: Inserisci link a discussione
  - type: input
    id: voto
    attributes:
      label: Link votazione
      placeholder: Inserisci link a votazione