title: "[PROPOSTA] "
labels: ["proposta"]
body:
  - type: textarea
    id: descrizione
    attributes:
      label: Contesto
      placeholder: Descrivi contesto, obiettivi e destinatari
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Proposta
      placeholder: Es. commenti, adesioni, revisione
    validations:
      required: true
  - type: input
    id: riferimenti
    attributes:
      label: Link / riferimenti
      placeholder: Documenti, discussioni, risorse esterne
  - type: input
    id: link-votazione
    attributes:
      label: Link votazione
      placeholder: Inserisci link alla votazione quando approvata
