title: "Domanda"
labels: ["q&a"]
body:
  - type: textarea
    id: domanda
    attributes:
      label: Domanda
      description: Fai una domanda chiara e specifica
      placeholder: Es. Come si aderisce all’associazione?
    validations:
      required: true

  - type: textarea
    id: contesto
    attributes:
      label: Contesto
      description: Informazioni utili per capire meglio la domanda
      placeholder: Ruolo, situazione, riferimento normativo, ecc.

  - type: input
    id: riferimenti
    attributes:
      label: Link / riferimenti
      placeholder: Documentazione, pagine interne, discussioni correlate

